-- Encourage Me Supabase setup
-- Run this in Supabase Dashboard -> SQL Editor before starting the API.
-- The backend uses the service-role key and therefore does not rely on client RLS.

create table if not exists users (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text,
  google_id text unique,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamp not null default now()
);

create table if not exists emotion_entries (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  emotion text not null,
  message text,
  ai_response text,
  created_at timestamp not null default now()
);

create table if not exists journal_entries (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  content text not null,
  entry_type text not null default 'reflection',
  created_at timestamp not null default now()
);

create table if not exists journal_attachments (
  id integer generated by default as identity primary key,
  journal_entry_id integer not null references journal_entries(id) on delete cascade,
  file_name text,
  content_type text not null,
  data text not null,
  created_at timestamp not null default now()
);

create table if not exists favorites (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  content_type text not null,
  content_id text not null,
  title text,
  thumbnail text,
  channel text,
  extra text,
  created_at timestamp not null default now()
);

create table if not exists settings (
  id integer generated by default as identity primary key,
  user_id integer not null unique references users(id) on delete cascade,
  notifications_enabled boolean not null default true,
  reminder_time text not null default '20:00',
  reminder_frequency text not null default 'daily',
  calendar_theme_id text,
  calendar_background_image text,
  created_at timestamp not null default now()
);

create table if not exists password_reset_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  token text not null unique,
  expires_at timestamp not null,
  used boolean not null default false,
  created_at timestamp not null default now()
);

create table if not exists testimonials (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  text text not null,
  created_at timestamp not null default now()
);

create table if not exists testimonial_attachments (
  id integer generated by default as identity primary key,
  testimonial_id integer not null references testimonials(id) on delete cascade,
  file_name text,
  content_type text not null,
  data text not null,
  created_at timestamp not null default now()
);

create table if not exists testimonial_comments (
  id integer generated by default as identity primary key,
  testimonial_id integer not null references testimonials(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  content text not null,
  created_at timestamp not null default now()
);

create table if not exists testimonial_likes (
  id integer generated by default as identity primary key,
  testimonial_id integer not null references testimonials(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  created_at timestamp not null default now(),
  unique (testimonial_id, user_id)
);

create table if not exists consultants (
  id integer generated by default as identity primary key,
  name text not null,
  title text not null,
  bio text,
  specialties text,
  experience_summary text,
  plan_tier text not null default 'basic',
  photo_url text,
  contact_email text,
  contact_phone text,
  is_active boolean not null default true,
  created_at timestamp not null default now()
);

create table if not exists support_organizations (
  id integer generated by default as identity primary key,
  name text not null,
  description text,
  category text,
  country text not null default 'Uganda',
  location text,
  phone text,
  phone_note text,
  email text,
  website text,
  emergency boolean not null default false,
  created_at timestamp not null default now()
);

create table if not exists consultation_purchases (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  plan_tier text not null,
  amount integer not null,
  currency text not null default 'UGX',
  tx_ref text not null unique,
  flutterwave_transaction_id text,
  status text not null default 'pending',
  created_at timestamp not null default now(),
  verified_at timestamp
);

create index if not exists idx_users_email on users(email);
create index if not exists idx_users_google_id on users(google_id);
create index if not exists idx_emotion_entries_user_id on emotion_entries(user_id);
create index if not exists idx_journal_entries_user_id on journal_entries(user_id);
create index if not exists idx_favorites_user_id on favorites(user_id);
create index if not exists idx_password_reset_tokens_token on password_reset_tokens(token);
create index if not exists idx_testimonials_created_at on testimonials(created_at desc);
create index if not exists idx_consultation_purchases_tx_ref on consultation_purchases(tx_ref);

-- Storage bucket for avatars and journal/testimonial attachments.
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

drop policy if exists "Public media is readable" on storage.objects;
drop policy if exists "Backend service role manages media" on storage.objects;

create policy "Public media is readable"
on storage.objects for select
using (bucket_id = 'media');

create policy "Backend service role manages media"
on storage.objects for all
using (bucket_id = 'media')
with check (bucket_id = 'media');
